# https://www.elastic.co/guide/en/logstash/current/docker.html
FROM docker.elastic.co/logstash/logstash:7.15.1

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
