# https://www.elastic.co/guide/en/logstash/current/docker.html
FROM docker.elastic.co/logstash/logstash-oss:7.10.2

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
