version: "2"

services:
  #
  # Nexus : code artifact and docker images repository
  #
  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    environment:
      - VIRTUAL_HOST=nexus.local
    depends_on: 
      - nginx-proxy
  
  sonar:
    image: sonarqube:lts
    ports:
      - "9000:9000"
    environment:
      - VIRTUAL_HOST=sonar.local
      - VIRTUAL_PORT=9000
    depends_on: 
      - nginx-proxy

  elasticsearch:
    build:
      context: ./apps/elasticsearch/
    volumes:
      - ./apps/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    build:
      context: ./apps/logstash/
    volumes:
      - ./apps/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./apps/logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: ./apps/kibana/
    volumes:
      - ./apps/kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    environment:
      - VIRTUAL_HOST=super.local
      - VIRTUAL_PORT=5601
    networks:
      - elk
      - public
    depends_on:
      - elasticsearch
      - apm-server
      - nginx-proxy

  apm-server:
    build:
      context: ./apps/apm/
    volumes:
      - ./apps/apm/config/:/usr/share/apm/config:ro
    ports:
      - "8200:8200"
    networks:
      - elk
      - public
    depends_on:
      - elasticsearch

  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - ROOT_URL=http://gitea.local
      - VIRTUAL_HOST=gitea.local:3000,git.local:222
    restart: always
    depends_on:
      - nginx-proxy
    volumes:
      - ./apps/gitea/data:/data
    ports:
      - "3000:3000"
      - "222:22"

  drone-server:
    image: drone/drone:1
    ports:
      - 8000:80
      - 9000
    volumes:
      - ./apps/drone/data:/var/lib/drone/
    restart: always
    depends_on:
      - nginx-proxy
      - gitea
    environment:
      - DRONE_OPEN=true
      - DRONE_SERVER_HOST=http://drone.local
      - DRONE_GITEA=true
      - DRONE_GITEA_SERVER=http://gitea.local:3000
      - DRONE_GITEA_SKIP_VERIFY=true
      - DRONE_SECRET=secret
      - DRONE_NETWORK=public
      - VIRTUAL_HOST=drone.local
      - VIRTUAL_PORT=8000
    networks:
      - drone
      - public

  drone-agent:
    image: drone/agent:0.8
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:8000
      - DRONE_SECRET=secret
    networks:
      - drone

  oauth:
    image: qlik/simple-oidc-provider

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  # lightouse reports server
  # see this for lhci configuration https://github.com/GoogleChrome/lighthouse-ci/
  light:
    image: patrickhulce/lhci-server
    ports:
      - "9001:9001"
    volumes:
      - ./apps/data/lhci:/data
    environment:
      - VIRTUAL_HOST=light.local
      - VIRTUAL_PORT=9001
    depends_on:
      - nginx-proxy

  # ldap database
  #
  www:
    build: ./apps/apm-ssr/
    user: node
    ports:
      - "4000:4000"
    environment:
      - VIRTUAL_HOST=home.local
      - APM_SERVER=apm.local

  # ldap database
  #
  whois:
    image: osixia/openldap
    volumes:
      - ./apps/whois/config/:/usr/share/nginx
    environment:
      - VIRTUAL_HOST=whois.local

  # oauth2 provider
  # https://www.ory.sh/run-oauth2-server-open-source-api-security/
  # 
  hydra:
    image: oryd/hydra:v1.4.2
    environment:
      - VIRTUAL_HOST=auth.local
      - SECRETS_SYSTEM=${SECRETS_SYSTEM}
      - DSN=$DSN
      - URLS_SELF_ISSUER=http://127.0.0.1:9000/
      - URLS_CONSENT=http://127.0.0.1:4200/consent
      - URLS_LOGIN=http://127.0.0.1:9020/login
    ports: 
      - 7000:4444
      - 7001:4445

networks:
  elk:
    driver: bridge
  public:
  drone:
